[package]
name = "texrs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.26"
csv = "1.1"

[profile.release]
strip = true
opt-level = "z"
lto = true